name: cut release

on:
  pull_request:
    branches: main
    types: closed
  workflow_dispatch:

permissions: {}

jobs:
  release:
    if:
      github.event_name == 'workflow_dispatch' || (github.event.pull_request.user.login
      == 'github-actions[bot]' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to update release
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          pip-version: "25.3"

      - name: Get version
        id: version
        run: echo "version=$(python scripts/release.py -V)" >> "$GITHUB_OUTPUT"

      - name: Get changelog
        id: changelog
        run: python scripts/release.py -C >> latest-changelog.md

      - name: Edit release
        run: gh release edit "$VERSION" -F latest-changelog.md --draft=false
        env:
          VERSION: ${{ steps.version.outputs.version }}

  update-stable:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: release
    permissions:
      contents: write # Needed to push to stable

    steps:
      - name: Checkout stable branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: stable
          fetch-depth: 0
          persist-credentials: true # needed for `git push` below

      - name: Update stable branch to release tag & push
        run: |
          git reset --hard "$VERSION"
          git push
        env:
          VERSION: ${{ needs.release.outputs.version }}

  new-changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: release
    permissions:
      contents: write # Needed to push to new branch
      pull-requests: write # Needed to create PR
    steps:
      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true # Needed for git-auto-commit-action

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          pip-version: "25.3"

      - name: Add new changelog
        run: python scripts/release.py -a

      - name: Commit new changelog
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Add new changelog
          branch: ci/new-changelog
          create_branch: true

      - name: Create PR
        run: |
          gh pr create \
            -t "Add new changelog" -b "" \
            -l "ci: skip news" -l "C: maintenance" \
            -a $USER
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USER: ${{ github.triggering_actor }}
